/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;
import civitas.CivitasJuego;
import civitas.Diario;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import civitas.OperacionInmobiliaria;
import civitas.Jugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josemanu
 */
public class CivitasView extends javax.swing.JFrame implements Vista {

    private CivitasJuego juego;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        Dado.createInstance(this);
    }
    
    public void setCivitasJuego (CivitasJuego juego) {
        
        this.juego = juego;
        setVisible(true);
        
    }
    
    public void actualiza() {
    
        jugadorPanel1.setJugador(juego.getJugadorActual());
        casillaPanel1.setCasilla(juego.getCasilla());
        rankingLabel.setVisible(false);
        rankingTexto.setVisible(false);
        jScrollPane1.setVisible(false);
        
        
        if (juego.finalDelJuego()) {
            
            rankingLabel.setVisible(true);
            rankingTexto.setVisible(true);
            String salida = "";
            for (int i = 0; i < juego.ranking_pub().size(); i++)
                salida+= (i+1) + ". " + juego.ranking_pub().get(i);
                
            rankingTexto.setText(salida);
            
            repaint();
            revalidate();
            
        }
            
    
    }

    public void pausa() {
    
        int val = JOptionPane.showConfirmDialog(null, "¿Continuar?", "Siguiente paso", JOptionPane.YES_NO_OPTION);
        
        if (val==1) System.exit(0);
    
    }

    public Respuesta comprar() {
        
        int opcion = 1 - JOptionPane.showConfirmDialog(null, "¿Quiere comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        Respuesta respuesta = Respuesta.NO;
        
        if (opcion ==  0)
            respuesta = Respuesta.NO;
        
        if (opcion == 1)
            respuesta = Respuesta.SI;
        
        return respuesta;
                
    }

    public OperacionInmobiliaria elegirOperacion() {
        
        GestionarDialog gestionar = new GestionarDialog(this);
        
        int operacion = gestionar.getGestion();
        OperacionInmobiliaria op = OperacionInmobiliaria.TERMINAR;
        
        if (operacion == 0)
            op = OperacionInmobiliaria.CONSTRUIR_CASA;
        
        if (operacion == 1)
            op = OperacionInmobiliaria.CONSTRUIR_HOTEL;
        
        return op;
        
    }

    public int elegirPropiedad() {
    
        PropiedadDialog propiedad = new PropiedadDialog(this, juego.getJugadorActual());
        
        int eleccion = propiedad.getPropiedad();
        
        return eleccion;
    
    }

    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
    
        siguienteOpTexto.setText(operacion.toString());
        
        if (operacion == OperacionJuego.AVANZAR)
            //Dado.createInstance(this);
            //Dado.getInstance().setVisible(true);
        
        repaint();
    
    }

    public void mostrarEventos() {
    
        if (!Diario.getInstance().getEventos().isEmpty()) {
            DiarioDialog diarioD = new DiarioDialog(this);
        }    
        
    }
    
    public void mostrarEstado() {
    
        if (!juego.finalDelJuego()) {
          
          System.out.println(juego.getJugadorActual().toString());
          System.out.println(juego.getCasilla().toString());
          
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Título = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        casillaPanel1 = new GUI.CasillaPanel();
        siguienteOperacion = new javax.swing.JLabel();
        siguienteOpTexto = new javax.swing.JTextField();
        rankingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Título.setText("Jugador y Casilla Actual");

        siguienteOperacion.setText("Siguiente operación");

        siguienteOpTexto.setEditable(false);
        siguienteOpTexto.setText("jTextField1");

        rankingLabel.setText("Ranking");

        rankingTexto.setColumns(20);
        rankingTexto.setRows(5);
        jScrollPane1.setViewportView(rankingTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rankingLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siguienteOperacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(siguienteOpTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(Título))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Título)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siguienteOperacion)
                            .addComponent(siguienteOpTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(rankingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Título;
    private GUI.CasillaPanel casillaPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JTextArea rankingTexto;
    private javax.swing.JTextField siguienteOpTexto;
    private javax.swing.JLabel siguienteOperacion;
    // End of variables declaration//GEN-END:variables
}
